version: "3.8"
services:
  api:
    container_name: command-ai-api
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "8081:9000"
    environment:
      - RUST_LOG=debug
      - AWS_ACCESS_KEY_ID=dummy-access-key-id
      - AWS_SECRET_ACCESS_KEY=dummy-secret-key
      - AWS_SESSION_TOKEN=dummy-ssession-token
    entrypoint: ["cargo", "lambda", "watch", "-a", "0.0.0.0", "-p", "9000"]
